### ISSUE TITLE
recomendações de boas práticas

### ISSUE THREAD

**Issue by pedsmoreira** [victorgaard/mighty-weather#5]
Inconsistências no código me incomodam bastante porque eles quebram o fluxo de raciocínio natural.

cada doido com suas manias, e cada dev com suas práticas, aqui vão algumas que eu gosto de seguir

1. não colocar a implementação em `index.js` - tipo aqui https://github.com/victorgaard/mighty-weather/blob/main/src/Components/App/index.js . Eu recomendo fazer `App/App.js` + `App/index.js` e no `index.js` vc faz `export * from './App.js`. É uma coisa boba, mas fica mais fácil procurar o arquivo que você quer quando eles não são todos chamados index.js
2. usar export com nome ao invés de default - export default parece legal porque só pode ter um por arquivo. O problema dele é que é difícil refatorar o código. Suponha que vc tem um componente chamado `AnjoDaGuarda`, depois ele passa a se chamar `AnjoAlegre`, a importação dele pode ser `import AnjoDaGuarda from './AnjoAlegre` e vai continuar funcionando, mas quem for ler o código vai ficar confuso do porque isso está acontecendo. Outro caso comum é copiar código de um arquivo pra outro e esquecer de mudar o nome do componente. Além disso, com export default vc n pode facilmente `export * from './`, vc tem que `export { default as default } from './...`
3. formatador de código - https://prettier.io/
4. ESLint - https://eslint.org/. Essa ferramenta serve pra apontar padrões no código que você considerar indesejáveis. Algumas empresas fazem os próprios, outras usam padrões de outras pra evitar o bikeshedding. Um dos padrões mais usados é do AirBnb https://www.npmjs.com/package/eslint-config-airbnb. Ao invés de eu mesmo te fazer as sugestões de melhorias, nesse momento eu acho que vai te ajudar mais vc adicionar os ESLint AirBnb e ver o que ele vai te apontar

**Comment by victorgaard** [comment]
Wooow! Brigadão por todas recomendações @pedsmoreira 
Vão me ajudar demais!🤘💯
